modLoader="javafml"
loaderVersion="${loader_version_range}" 
license="${mod_license}"

[[mods]] 
    modId="${mod_id}"
    version="${mod_version}"
    displayName="${mod_name}"
    logoFile="icon.png"
    authors="${mod_authors}"
    description='''${mod_description}'''

[[mixins]]
    config="${mod_id}.mixins.json"

[[dependencies."${mod_id}"]]
    modId="neoforge" 
    type="required" 
    versionRange = "${neo_version_range}"
    ordering="AFTER"
    side="BOTH"

[[dependencies."${mod_id}"]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="AFTER"
    side="BOTH"

[[dependencies."${mod_id}"]]
    modId="touhou_little_maid"
    type="required"
    versionRange="[1.3.3,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies."${mod_id}"]]
    modId="create"
    type="required"
    versionRange="[6.0.0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies."${mod_id}"]]
    modId="create_connected"
    type="optional"
    versionRange="[1.0.0,)"
    ordering="AFTER"
    side="BOTH"
